

networks:
  pg-network:

volumes:
  ny_taxi_postgres_data:
  pgadmin_data:

services:
  pgdatabase:
    image: postgres:18
    #container_name: pgdatabase
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    networks:
      - pg-network
    ports:
      - "5432:5432"
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    # container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - pg-network
    ports:
      - "8085:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  data-loader:
    build:
      context: .
      dockerfile: Dockerfile
    image: taxi_ingest:v001  # Use your existing image name
    networks:
      - pg-network
    depends_on:
      - pgdatabase
